#!/usr/bin/env ruby

require 'wp_event'
require 'optparse'
require 'json'

extend WPEvent::CLI::Logging
extend WPEvent::CLI
extend WPEvent::CLI::Tool

options = {}

option_parser = OptionParser.new do |opts|
  opts.banner = <<~USAGE
    Usage: #{$PROGRAM_NAME} [options] FILE

    Sync a list of referees with referees registered in wordpress instance

    FILE is supposed to be a json array of hashes (uuid:, firstname:, lastname:, description:, image_url:)
    Alternatively, will read from STDIN.
    Will exit with 0 on success

  USAGE

  opts.on("-s", "--image-store=PATH", "Path where to search images (to upload)") do |s|
    options[:image_store] = s
  end

  opts.separator "Common options"
  opts.on("-v", "--[no-]verbose", "Run verbosely") do |v|
    options[:verbose] = v
  end
  opts.on_tail("-h", "--help", "Show this message and exit") do
    puts opts
    exit
  end
  opts.on_tail("--version", "Show version and exit") do
    puts WPEvent::VERSION
    exit
  end
end

# Process options
option_parser.parse!

WPEvent::CLI::Tool.init_logger verbose: options[:verbose]

debug "Starting referee sync (#{WPEvent::VERSION})"


if ARGV.length != 1 && STDIN.tty?
  STDERR.puts "Please provide json input file."
  puts option_parser
  exit 1
end

begin
  Compostr.load_conf
rescue Errno::ENOENT
  exit_with 3, "Config file (compostr.conf) not found."
end

input = ARGV.length == 1 ? File.open(ARGV[0]) : STDIN
json = input.read

referees = JSON.parse json#, symbolize_names: true
# TODO nicer parse error display, begin..rescue

referee_cache  = Compostr::EntityCache.new(WPEvent::CustomPostTypes::Referee)
media_cache    = Compostr::MediaLibraryCache.new
image_uploader = Compostr::ImageUploader.new options[:image_store], media_cache

syncer = Compostr::Syncer.new image_uploader

referees.each_with_index do |referee, idx|

  wp_referee = referee_cache.in_mem_lookup(referee["uuid"])

  info "(#{idx + 1}/#{referees.length}): Processing referee with uuid #{referee['uuid']}"

  # Transform string keys to symbol keys.
  # This **could** be done directly while parsing the json:
  #   x = JSON.parse json, symbolize_names: true
  referee.keys.each do |key|
    referee[(key.to_sym rescue key) || key] = referee.delete(key)
  end

  debug "Referee from cache: #{wp_referee}"

  syncer.merge_push WPEvent::CustomPostTypes::Referee.new(**referee), WPEvent::CustomPostTypes::Referee.from_content_hash(wp_referee)
end

exit 0
